# .readthedocs.yaml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      - pip install poetry==1.2.0b1
      - poetry config virtualenvs.create false
      - poetry install --with doc

mkdocs:
  configuration: mkdocs.yml
