---
codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 80..100

  status:
    project:
      default:
        target: 90
        threshold: 10%
    patch:
      default:
        target: 90
        threshold: 10%
    changes: False

comment: false
