[project]
name = "pixi"
version = "0.0.1.dev"
description = "A demo jewellery store that uses Hyx for resiliency"
authors = [
    {name = "Roman Hlushko", email = "roman.glushko.m@gmail.com"},
]
dependencies = []
requires-python = ">=3.12"
license = {text = "Apache 2.0"}
